#!/bin/bash

# Slackware build script for python3-proton-vpn-api-core

# Copyright 2026 Isaac Yu <isaacyu@protonmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=python3-proton-vpn-api-core
VERSION=${VERSION:-5.5.11}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

SRCNAM=python-proton-vpn-api-core

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  CARGOTARGET="--target i686-unknown-linux-gnu"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  CARGOTARGET="--target $ARCH-unknown-linux-gnu"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  CARGOTARGET="--target $ARCH-unknown-linux-gnu"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  CARGOTARGET=""
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM-$VERSION
tar xvf $CWD/$SRCNAM-$VERSION.tar.gz
cd $SRCNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Fix ProTun protocol (patch taken from Arch repo) 
patch -p1 < $CWD/fix-protun-protocol.patch

# Build offline using vendored .crate files
cat << EOF >> .cargo/config.toml
[source.crates-io]
registry = 'https://github.com/rust-lang/crates.io-index'
replace-with = 'vendored-sources'

[source.vendored-sources]
directory = '$(pwd)/vendor'
EOF

mkdir vendor
(
  cd vendor

  grep -h -A 4 "\[\[package\]\]" \
      $(find "../" -maxdepth 1 -mindepth 1 -name Cargo.lock | tr '\n' ' ') | \
      sed 's/[[:space:]]*=[[:space:]]*/=/g;s/^--//;s/^\[\[/--\n[[/' | \
      awk 'BEGIN { RS = "--\n" ; FS="\n" } { print $2, $3, $4, $5 }' | \
      sed 's/"//g;s/name=//;s/ version=/=/' | \
      grep " source=" | \
      sed 's/ dependencies=.*$//' | \
      sed 's/ source=[^ ]*//' | \
      sed 's/ checksum=/=/' | \
      sort -u | \
      while read -r dep ; do

    cksum="$(printf "%s\n" "$dep" | cut -d= -f3)"
    ver="$(printf "%s\n" "$dep" | cut -d= -f2)"
    dep="$(printf "%s\n" "$dep" | cut -d= -f1)"

    tar xvf $CWD/$dep-$ver.crate

    touch $dep-$ver/.cargo-ok

    {
      printf "{\n"
      printf '    "files": {\n'

      (
        cd $dep-$ver
        find . -type f -print0 | xargs -0 sha256sum | sed -n '/\.cargo-checksum\.json/!p' | sed 's/\.\///;s/^\([^ ]*\)[[:space:]][[:space:]]*\(.*\)$/"\2":"\1",/'
      ) | sed '$ s/,$//'

      printf "    },\n"
      printf '    "package": "%s"'  "$cksum"

      printf "}\n"
    } > $dep-$ver/.cargo-checksum.json
  done
)

export PATH="/opt/rust/bin:$PATH"
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="/opt/rust/lib$LIBDIRSUFFIX"
else
  export LD_LIBRARY_PATH="/opt/rust/lib$LIBDIRSUFFIX:$LD_LIBRARY_PATH"
fi

sed -i \
  -e "$(printf 's|%s|%s|' e96081b45cc7a830262dcbac2a79b58bc312aab0672c4c1c51fd8c28b03ca987 \
  d6cbef9a3ddc5f97501607f1a689c459a1894069745b4cede7c519b71bb64434)" \
  -e "$(printf 's|%s|%s|' 8e4b9d4c0cb1aa4096f9f7bdabc120323c7b6d110efba90d258c0150a65a7e12 \
  4c2654d02228a2e4ccb4edf1883cb2838d9640e19012f75e0cad7afcb468f2d5)" \
  -e "$(printf 's|%s|%s|' 90c6da77725af99bfa1dd9bed7b7c3481c087cd89a8a0a1d7e45e15ed3a3377d \
  0a7b06dd92ace9b23a49beeb33511ef6bcc04355e314f1f8ee8aadbe8c613b98)" \
  -e "$(printf 's|%s|%s|' 161e33ea4b9b564a0910b8948ef55bf8183504f0c5911e2354cfabcebae25910 \
  e6a48e2f0e60ec3cca1c6d0c7c3fe178a359e3bfcd26ea6668a862787884c26e)" \
  -e "$(printf 's|%s|%s|' fcd725b3baebb44befaf9a37e158e7cbfb044e32324469ae765c8e052755f323 \
  228f7a3f5b66a5cea2dc522efa212b3059413a487b7e4af1d8f549694a54741b)" \
  -e "$(printf 's|%s|%s|' 23e1d1a18fc6a68c4622b25e7a45fd8e50d41d2607e71a346b986691a3b1507b \
  64499d4117fcba0ad93e6444cd75dbc5985752d80b645762a999be305c57ceeb)" \
  Cargo.lock

CARGO_HOME=.cargo \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
cargo build --offline --release $CARGOTARGET \
  --bin nm-protun-service \
  --bin nm-protun-auth-dialog \
  --lib \
  --features 'protun,nm_protun_auth_dialog,python,core,local_agent'

install -Dm755 target/release/libproton_vpn_platform.so proton/vpn/platform.abi3.so

python3 setup.py install --root=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

install -Dm755 target/release/nm-protun-service $PKG/usr/libexec/nm-protun-service
install -Dm755 target/release/nm-protun-auth-dialog $PKG/usr/libexec/nm-protun-auth-dialog
install -Dm644 resources/nm-protun-service.conf $PKG/usr/share/dbus-1/system.d/nm-protun-service.conf

install -d "$PKG/usr/lib/NetworkManager/VPN"
sed -e 's|program=.*|program=/usr/libexec/nm-protun-service|' \
    -e 's|auth-dialog=.*|auth-dialog=/usr/libexec/nm-protun-auth-dialog|' \
  resources/nm-protun.name \
  > "$PKG/usr/lib/NetworkManager/VPN/nm-protun.name"

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a LICENSE README.md $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
